project:
  type: website
  output-dir: public

website:
  title: "ConvertingAppendix"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: appendix_a1.qmd
        text: A.1 Introduction
      - href: appendix_a2.qmd
        text: A.2 Sequences and Sums
      - href: appendix_a3.qmd
        text: A.3 Control Statements
      - href: appendix_a4.qmd
        text: A.4 Functions
      - href: appendix_a5.qmd
        text: A.5 Number Representation
      - href: appendix_a6.qmd
        text: A.6 Answers
      - href: appendix_all.qmd
        text: A.All Combined
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
